config/routes.rb
Googlemap::Application.routes.draw do
  root :to => "places#index"
  
  resources :places

	match 'places/:id' => 'places#show', :as => 'search'

end

app/models/place.rb
class Place < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :long
	validates_presence_of :lat
	
	before_create :autostatus
	
	def autostatus
		self.status = "Pending"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.xml
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @places }
    end
  end
  
  def search
  	@place = Place.find(params[:name])
  	place = Place.find_by_name(@place.name)
  	
  	if place
  		flash[:notice] = "found."
  	else
  		flash[:notice] = "gubaon"
  	end
  	
  	respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @place }
    end
  end
  
  
  
  
  
  def login
	  if request.post? and params[:user]
		@user = User.new(params[:user])
	 
		user = User.find_by_username(@user.username)
		
		if user and user.password_matches?(@user.password)
		  session[:user_id] = user.id
		  user.save
	 
		  if user.account.eql?("admin")
		    redirect_to :action => "admin"
		  else
		    redirect_to :action => "user"
		  end
		else
		  flash[:notice] = "Sorry, no user was found with that username/password combination."
		end
	  end
  end
  
  
  
  
  
  
  
  
  
  
  

  # GET /places/1
  # GET /places/1.xml
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # GET /places/new
  # GET /places/new.xml
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.xml
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to(@place, :notice => 'Place was successfully created.') }
        format.xml  { render :xml => @place, :status => :created, :location => @place }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.xml
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to(@place, :notice => 'Place was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.xml
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to(places_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Googlemap</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Lat</th>
    <th>Long</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.name %></td>
    <td><%= place.status %></td>
    <td><%= place.lat %></td>
    <td><%= place.long %></td>
    <td><%= link_to 'Show', place %></td>
    <td><%= link_to 'Edit', edit_place_path(place) %></td>
    <td><%= link_to 'Destroy', place, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<p>
  <b>Name:</b>
  <%= @place.name %>
</p>

<p>
  <b>Status:</b>
  <%= @place.status %>
</p>

<p>
  <b>Lat:</b>
  <%= @place.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @place.long %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

<br />
<script>

  var gMap2 = new GMap2();

  function mapClick(gMarker, gLatLng) {
    if (gMarker) {
      displayMarkerPosition(gMarker);
    } else if (gLatLng) {
      createLocationMarker(gLatLng);
    }
  }

  function createLocationMarker(gLatLng) {
    var gMarker = new GMarker(gLatLng, {draggable: true, bouncy: true});
    gMap2.addOverlay(gMarker);

    displayMarkerPosition(gMarker);

    GEvent.addListener(gMarker, "dragstart", closeMapInfoWindow);

    GEvent.addListener(gMarker, "dragend", function() {
      displayMarkerPosition(gMarker);
    });
  }

  function closeMapInfoWindow() {
    gMap2.closeInfoWindow();
  }

  function displayMarkerPosition(gMarker) {
    GAsync(gMarker, 'getPoint', gMap2, 'getBounds', 'getSize', function(gLatLng, gLatLngBounds, gSize) {
      gMarker.openInfoWindowHtml(gpsString(gLatLng, gLatLngBounds, gSize));
    });
  }

  function gpsString(gLatLng, gLatLngBounds, gSize) {
    var ne = gLatLngBounds.getNorthEast();
    var sw = gLatLngBounds.getSouthWest();

    var degreesPerPixel = (ne.lat() - sw.lat()) / gSize.height;
    var goodDigits = Math.ceil(- Math.log(degreesPerPixel) / Math.log(10))
 
    var roundedLatLng = roundGLatLng(gLatLng, goodDigits);
 
    return "GPS: " + roundedLatLng.lat() + ", " + roundedLatLng.lng();
  }

  function roundGLatLng(gLatLng, goodDigits) {
    return new GLatLng(roundNumber(gLatLng.lat(), goodDigits), roundNumber(gLatLng.lng(), goodDigits));
  }

  function roundNumber(number, goodDigits) {
    var power = Math.pow(10, Math.ceil(goodDigits));
    return Math.round(number * power) / power;
  }

  GEvent.addListener(gMap2, "click", mapClick);

</script>
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Cebu+City,+Philippines&amp;aq=0&amp;sll=37.370157,-95.712891&amp;sspn=28.922657,86.572266&amp;ie=UTF8&amp;hq=&amp;hnear=Cebu+City,+Cebu,+Central+Visayas,+Philippines&amp;z=11&amp;ll=10.359189,123.863454&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Cebu+City,+Philippines&amp;aq=0&amp;sll=37.370157,-95.712891&amp;sspn=28.922657,86.572266&amp;ie=UTF8&amp;hq=&amp;hnear=Cebu+City,+Cebu,+Central+Visayas,+Philippines&amp;z=11&amp;ll=10.359189,123.863454" style="color:#0000FF;text-align:left">View Larger Map</a></small>